{
 "title": "MAIN",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Average flight distance per zone",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "db.distancesRT.aggregate([\n{\"$project\": {\"ts\": \"$window.start\", \"name\": \"$at_zone\", \"value\": \"$avgdistances\", \"_id\": 0}}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Active flights per zone",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.fpzRT.aggregate([\n{\"$group\": {\"_id\": {\"ts\": \"$window.start\", \"zone\": \"$at_zone\"}, \"tot\": {\"$sum\": \"$count\"}}},\n{\"$sort\": {\"_id.ts\": -1}},\n{\"$project\": {\"ts\": \"$_id.ts\", \"name\": \"$_id.zone\", \"value\": \"$tot\", \"_id\": 0}}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Flights yesterday",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.flights.aggregate([\n{\"$match\": {\"origin_airport_iata\": {\"$ne\": \"N/A\"}, \"destination_airport_iata\": {\"$ne\": \"N/A\"}}},\n{\"$addFields\": {\"ts\": {\"$substr\": [\"$ts\", 0, 10]}}},\n{\"$addFields\": {\"ts\": {\"$dateFromString\": {\"dateString\": \"$ts\"}}}},\n{\"$group\": {\"_id\": {\"ts\": \"$ts\", \"flid\": \"$id\"}, \"tot\": {\"$sum\": 1}}},\n{\"$group\": {\"_id\": \"$_id.ts\", \"total\": {\"$sum\": \"$tot\"}}},\n{\"$project\": {\"name\": \"day\", \"value\": \"$total\", \"ts\": \"$_id\", \"_id\": 0}},\n{\"$sort\": {\"ts\": -1}},\n{\"$skip\": 1},\n{\"$limit\": 1}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Most departures from",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.flights.aggregate([\n{\"$match\": {\"origin_airport_iata\": {\"$ne\": \"N/A\"}, \"destination_airport_iata\": {\"$ne\": \"N/A\"}}},\n{\"$addFields\": {\"ts\": {\"$substr\": [\"$ts\", 0, 10]}}},\n{\"$addFields\": {\"ts\": {\"$dateFromString\": {\"dateString\": \"$ts\"}}}},\n{\"$group\": {\"_id\": {\"id\": \"$id\", \"origin\": \"$origin_airport_iata\"}, \"tot\": {\"$sum\": 1}, \"ts\": {\"$first\": \"$ts\"}}},\n{\"$project\": {\"ts\": \"$ts\", \"origin\": \"$_id.origin\", \"id\": \"$_id.id\", \"tot\": 1, \"_id\": 0}},\n{\"$match\": {\"origin\": {\"$ne\": \"N/A\"}}},\n{\"$group\": {\"_id\": \"$origin\", \"tot\": {\"$sum\": 1}, \"ts\": {\"$first\": \"$ts\"}}},\n{\"$sort\": {\"tot\": -1}},\n{\"$project\": {\"ts\": \"$ts\", \"name\": \"$_id\", \"value\": \"$_id\", \"_id\": 0}},\n{\"$limit\": 1},\n{\"$lookup\": {\"from\": \"airports\", \"localField\": \"name\", \"foreignField\": \"iata\", \"as\": \"fromAir\"}},\n{\"$unwind\": {\"path\": \"$fromAir\"}},\n{\"$project\": {  \"name\": \"$fromAir.name\", \"value\":  \"$fromAir.name\", \"ts\": 1, \"_id\": 0}}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Aircraft most flew",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.flights.aggregate([\n{\"$match\": {\"origin_airport_iata\": {\"$ne\": \"N/A\"}, \"destination_airport_iata\": {\"$ne\": \"N/A\"}}},\n{\"$addFields\": {\"ts\": {\"$substr\": [\"$ts\", 0, 10]}}},\n{\"$addFields\": {\"ts\": {\"$dateFromString\": {\"dateString\": \"$ts\"}}}},\n{\"$group\": {\"_id\": {\"ts\": \"$ts\", \"craft\": \"$icao_24bit\", \"code\": \"$registration\"}, \"tot\": {\"$sum\": 1}}},\n{\"$project\": {\"ts\": \"$_id.ts\", \"name\": \"$_id.craft\", \"value\": \"$_id.code\",  \"_id\": 0}},\n{\"$match\": {\"craft\": {\"$ne\": \"N/A\"}, \"code\": {\"$ne\": \"N/A\"}}},\n{\"$sort\": {\"value\": -1}},\n{\"$limit\": 1}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Flights count per airline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "db.flights.aggregate([\n{\"$match\": {\"origin_airport_iata\": {\"$ne\": \"N/A\"}, \"destination_airport_iata\": {\"$ne\": \"N/A\"}}},\n{\"$addFields\": {\"ts\": {\"$substr\": [\"$ts\", 0, 10]}}},\n{\"$addFields\": {\"ts\": {\"$dateFromString\": {\"dateString\": \"$ts\"}}}},\n{\"$group\": {\"_id\": {\"ts\": \"$ts\", \"flid\": \"$id\", \"line\": \"$airline_icao\"}, \"tot\": {\"$sum\": 1}}},\n{\"$group\": {\"_id\": {\"ts\": \"$_id.ts\", \"line\": \"$_id.line\"}, \"total\": {\"$sum\": \"$tot\"}}},\n{\"$project\": {\"name\": \"$_id.line\", \"value\": \"$total\", \"ts\": \"$_id.ts\", \"_id\": 0}},\n{\"$sort\": {\"value\": -1}},\n{\"$match\": {\"name\": {\"$ne\": \"N/A\"}}}\n])",
     "type": "timeserie"
    }
   ]
  }
 ]
}